# Generated by Django 5.2.7 on 2025-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(blank=True, max_length=4, null=True)),
                ('lcode', models.CharField(blank=True, max_length=3, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('office', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('r', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Date-Time')),
                ('day', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
            ],
        ),
    ]
