# Generated by Django 5.2.7 on 2025-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcode', models.CharField(blank=True, max_length=3, null=True)),
                ('computer', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('bios', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
