# Generated by Django 5.2.7 on 2025-10-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='lvm',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='bios',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='computer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
